# Default values for cluster-odf.

# Application deployment context
context:  &context
  # Name of the global scope for this application (organisational tenant)
  scope: myscope
  # Name of the cluster running this application (platform tenant)
  cluster: default
  # Name of the environment for this application (ex: dev, factory, preprod or prod)
  environment: myenv
  # Component name of this application (logical tenant)
  component: mycomponent
  # Application name (functional tenant, default use Chart name)
  app: default-odf
  # Version name of this application (default use Chart appVersion)
  version: "4.19.11"

# configuration of the Storage service
odf:
  # Enable the deployment of a ODF cluster
  enabled: false
  # Activate the manager as a helm hook
  hooked: false
  # Redhat Network accesss user to the RH container catalog
  name: default-odf
  # Version of the ODF to use for this cluster
  version: "4.19.11"
  # Configure storage backend for this cluster
  storage:
    # Name of the storage pool
  - name: odf-deviceset
    # Number of OSD replicas
    replicas: 3
    # Number of OSD count
    count: 1
    # configuration of the OSD pods
    config: {}
    # Resource sizing for OSD pods
    resources: {}
    # placement rules for OSD pods
    placement: {}
    # preparePlacement rules for OSD pods
    preparePlacement: {}
    # Size of each OSD storage volume
    size: 512Gi
    # Storage class used to provision OSD storage
    storageClass: startx-aws-generic-retain

# Configuration of the project (see https://helm-repository.readthedocs.io/en/latest/charts/project)
project: 
  enabled: false
  context: 
    <<: *context
  project: 
    enabled: true
    type: namespace
    name: "openshift-storage"
    display_name: Operator ODF
    description: Openshift Container Storage operators configured by startx
  rbac: 
    enabled: false
  networkpolicy: 
    enabled: false
  limits: 
    enabled: false
  quotas: 
    enabled: false

# Configuration of the operator (see https://helm-repository.readthedocs.io/en/latest/charts/operator)
operator:
  enabled: false
  context: 
    <<: *context
  subscription:
    enabled: true
    name: "odf-operator"
    namespace: "openshift-storage"
    version: "v4.19.11-rhodf"
    operator: 
      channel: stable-4.19
      name: odf-operator
      installPlanApproval: Automatic
      # csv: odf-operator
      source: 
        name: redhat-operators
        namespace: openshift-marketplace
      config: 
        infra: true
  consolePlugin:
    enabled: true
    name: "odf-console"
    spec: |
      backend:
        service:
          basePath: /compatibility/
          name: odf-console-service
          namespace: openshift-storage
          port: 9001
        type: Service
      displayName: ODF Plugin
      i18n:
        loadType: ''
      proxy:
        - alias: provider-proxy
          authorization: UserToken
          endpoint:
            service:
              name: ux-backend-proxy
              namespace: openshift-storage
              port: 8888
            type: Service
        - alias: rosa-prometheus
          authorization: UserToken
          endpoint:
            service:
              name: prometheus
              namespace: openshift-storage
              port: 9339
            type: Service
        - alias: s3
          authorization: None
          endpoint:
            service:
              name: s3
              namespace: openshift-storage
              port: 443
            type: Service

  operatorGroup:
    enabled: true
    name: "openshift-storage"
    namespace: "openshift-storage"
    providedAPIs: "BackingStore.v1alpha1.noobaa.io,Backup.v1.postgresql.cnpg.noobaa.io,BucketClass.v1alpha1.noobaa.io,CSIAddonsNode.v1alpha1.csiaddons.openshift.io,CephBlockPool.v1.ceph.rook.io,CephBlockPoolRadosNamespace.v1.ceph.rook.io,CephBucketNotification.v1.ceph.rook.io,CephBucketTopic.v1.ceph.rook.io,CephCOSIDriver.v1.ceph.rook.io,CephClient.v1.ceph.rook.io,CephCluster.v1.ceph.rook.io,CephConnection.v1alpha1.csi.ceph.io,CephFilesystem.v1.ceph.rook.io,CephFilesystemMirror.v1.ceph.rook.io,CephFilesystemSubVolumeGroup.v1.ceph.rook.io,CephNFS.v1.ceph.rook.io,CephObjectRealm.v1.ceph.rook.io,CephObjectStore.v1.ceph.rook.io,CephObjectStoreUser.v1.ceph.rook.io,CephObjectZone.v1.ceph.rook.io,CephObjectZoneGroup.v1.ceph.rook.io,CephRBDMirror.v1.ceph.rook.io,ClientProfile.v1alpha1.csi.ceph.io,ClientProfileMapping.v1alpha1.csi.ceph.io,Cluster.v1.postgresql.cnpg.noobaa.io,ClusterImageCatalog.v1.postgresql.cnpg.noobaa.io,Database.v1.postgresql.cnpg.noobaa.io,Driver.v1alpha1.csi.ceph.io,EncryptionKeyRotationCronJob.v1alpha1.csiaddons.openshift.io,EncryptionKeyRotationJob.v1alpha1.csiaddons.openshift.io,FailoverQuorum.v1.postgresql.cnpg.noobaa.io,ImageCatalog.v1.postgresql.cnpg.noobaa.io,NamespaceStore.v1alpha1.noobaa.io,NetworkFence.v1alpha1.csiaddons.openshift.io,NetworkFenceClass.v1alpha1.csiaddons.openshift.io,NooBaa.v1alpha1.noobaa.io,NooBaaAccount.v1alpha1.noobaa.io,OCSInitialization.v1.ocs.openshift.io,ObjectBucket.v1alpha1.objectbucket.io,ObjectBucketClaim.v1alpha1.objectbucket.io,OperatorConfig.v1alpha1.csi.ceph.io,Pooler.v1.postgresql.cnpg.noobaa.io,Publication.v1.postgresql.cnpg.noobaa.io,Recipe.v1alpha1.ramendr.openshift.io,ReclaimSpaceCronJob.v1alpha1.csiaddons.openshift.io,ReclaimSpaceJob.v1alpha1.csiaddons.openshift.io,ScheduledBackup.v1.postgresql.cnpg.noobaa.io,StorageAutoScaler.v1.ocs.openshift.io,StorageClient.v1alpha1.ocs.openshift.io,StorageCluster.v1.ocs.openshift.io,StorageClusterPeer.v1.ocs.openshift.io,StorageConsumer.v1alpha1.ocs.openshift.io,Subscription.v1.postgresql.cnpg.noobaa.io,VolumeGroupReplication.v1alpha1.replication.storage.openshift.io,VolumeGroupReplicationClass.v1alpha1.replication.storage.openshift.io,VolumeGroupReplicationContent.v1alpha1.replication.storage.openshift.io,VolumeReplication.v1alpha1.replication.storage.openshift.io,VolumeReplicationClass.v1alpha1.replication.storage.openshift.io"

