# Default values for configuration of a STARTX cluster minimal pattern
# see values.yaml for explanation on each params
context:
  scope: startx
  cluster: default
  environment: infra
  component: argocd
  app: aoa-infra-min
  version: "0.1.0"

argocd_project:
  enabled: true
  list:
    - name: "aoa-infra-min"
      namespace: "openshift-gitops"
      sourceRepos:
        - 'https://gitlab.com/startx1/helm.git'
      destinations:
        - namespace: "*"
          server: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      roles:
      - name: admin
        description: All privileges to group admin in project
        policies:
        - p, role:startx-admin, *, *, */*, allow
        - g, system:cluster-admins, role:admin
        groups:
        - system:cluster-admins
        - admin
application:
  enabled: true
  list:
    - name: "app-infra-auth"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-auth.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-config"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-config.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-console"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-console.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-machine"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-machine.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-mustgather"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-mustgather.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-quaysec"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-quaysec.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
    - name: "app-infra-storage"
      namespace: "openshift-gitops"
      finalizer: true
      server: "https://kubernetes.default.svc"
      project: "aoa-infra-min"
      source:
        repo: "https://gitlab.com/startx1/helm.git"
        rev: "stable"
        path: "charts/cluster-argocd/"
      helm:
        valueFiles:
          - values-app-cluster-storage.yaml
        parameters:
          - name: context.cluster
            value: "example"
          - name: context.environment
            value: "dev"
          - name: argocd_repocreds.enabled
            value: "true"
          - name: argocd_project.enabled
            value: "true"
          - name: application.enabled
            value: "true"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - Validate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s
argocd_repocreds:
  enabled: true
  list: []

# Default project used par application namespace
project:
  enabled: false
  project:
    enabled: false
    name: openshift-gitops
