{{- if .Values.etcdBackup.enabled }}
{{- if and .Values.etcdBackup.s3_secret.s3_access_key .Values.etcdBackup.s3_secret.s3_secret_key }}
{{- $ns := .Values.etcdBackup.namespace | default "etcd-backup" -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "etcd-backup.s3SecretName" . | quote }}
  namespace: {{ $ns | quote }}
  labels:
    {{- include "etcd-backup.labels" . | nindent 4 }}
    app.kubernetes.io/name: etcd-backup-s3-secret
  annotations:
    {{- include "etcd-backup.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "11"
stringData:
  OCP_BACKUP_S3_ACCESS_KEY: {{ .Values.etcdBackup.s3_secret.s3_access_key | quote }}
  OCP_BACKUP_S3_SECRET_KEY: {{ .Values.etcdBackup.s3_secret.s3_secret_key | quote }}
{{- end }}
{{- end }}