{{- if .Values.etcdBackup.enabled }}
{{- $ns := .Values.etcdBackup.namespace | default "etcd-backup" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup
  namespace: {{ $ns | quote }}
  labels:
    {{- include "etcd-backup.labels" . | nindent 4 }}
    app.kubernetes.io/name: etcd-backup-sa
  annotations:
    {{- include "etcd-backup.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
  namespace: {{ $ns | quote }}
  labels:
    {{- include "etcd-backup.labels" . | nindent 4 }}
    app.kubernetes.io/name: etcd-backup-role
  annotations:
    {{- include "etcd-backup.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["privileged"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-sa-privileged
  namespace: {{ $ns | quote }}
  labels:
    {{- include "etcd-backup.labels" . | nindent 4 }}
    app.kubernetes.io/name: etcd-backup-rolebinding
  annotations:
    {{- include "etcd-backup.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-privileged-scc
subjects:
  - kind: ServiceAccount
    name: etcd-backup
    namespace: {{ $ns | quote }}
{{- end }}
