{{- if .Values.argocd_project }}{{- if .Values.argocd_project.enabled }}
{{- $defaultns := .Values.project.project.name | default "openshift-gitops" -}}
{{ range .Values.argocd_project.list }}
{{- $name := .name | default "default" -}}
{{- $namespace := .namespace | default $defaultns }}
---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ $name | quote }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "cluster-argocd.labels" $ | nindent 4 }}
    app.kubernetes.io/name: "{{- $name -}}-argocd_project"
  annotations:
    {{- include "cluster-argocd.annotations" $ | nindent 4 }}
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
{{- if .sourceRepos }}
    {{- toYaml .sourceRepos | nindent 4 }}
{{- else }}
    - '*'
{{- end }}
  destinations:
{{- if .destinations }}
    {{- toYaml .destinations | nindent 4 }}
{{- else }}
    - namespace: {{ $namespace | quote }}
      server: '*'
{{- end }}
  clusterResourceWhitelist:
{{- if .clusterResourceWhitelist }}
    {{- toYaml .clusterResourceWhitelist | nindent 4 }}
{{- else }}
    - group: '*'
      kind: '*'
{{- end }}
{{- if .roles }}
  roles:
    {{- toYaml .roles | nindent 4 }}
{{- else }}
  roles: []
{{- end }}

{{- end }}
{{- end }}{{- end }}
