# Default values for configuration of a STARTX cluster
# see values.yaml for explanation on each params
context: &context
  scope: startx
  cluster: default
  environment: infra
  component: acm
  app: startx-acm
  version: "2.16.2"
acm:
  enabled: false
  mch:
    enabled: false
    hooked: false
import:
  enabled: false
  hooked: false
create:
  enabled: false
  hooked: false
observability:
  enabled: false
  hooked: false
projectObservability: 
  enabled: false
  project: 
    enabled: false
    hooked: false
    name: "startx-acm-observability"
project: 
  enabled: true
  context: 
    <<: *context
  project: 
    enabled: true
    hooked: false
    type: namespace
    name: "openshift-acm-operator"
    display_name: Startx ACM
    description: ACM operators configured by startx
  rbac: 
    enabled: true
    groups: 
    - id: devops-view
      name: devops
      role: view
    - id: ops-admin
      name: ops
      role: admin
  networkpolicy: 
    enabled: false
  limits: 
    enabled: false
  quotas: 
    enabled: false
operator:
  enabled: true
  context: 
    <<: *context
  config:
    infra: true
  subscription:
    enabled: true
    name: "advanced-cluster-management"
    namespace: "openshift-acm-operator"
    version: "v2.16.2"
    operator: 
      channel: "release-2.16"
      name: advanced-cluster-management
      installPlanApproval: Automatic
      # csv: advanced-cluster-management
      source: 
        name: redhat-operators
        namespace: openshift-marketplace
      config: 
        infra: true
        # resources: 
        #   limits:
        #     cpu: 400m
        #   requests:
        #     cpu: 400m
  operatorGroup:
    enabled: true
    name: "openshift-acm-operator"
    namespace: "openshift-acm-operator"
    providedAPIs: "MultiClusterHub.v1.operator.open-cluster-management.io"
