{{- if .Values.backends }}
{{- if .Values.backends.enabled }}
{{- $namespace := .Values.orchestrator.spec.namespace | default "trident" -}}
{{- $root := . -}}
{{- range $idx, $backend := .Values.backends.list }}
{{- if $backend.credentials }}
{{- if and $backend.credentials.username $backend.credentials.password }}
{{- $secretName := $backend.credentials.secretName | default (printf "%s-secret" $backend.name) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName | quote }}
  namespace: "{{- $namespace -}}"
  labels:
    {{- include "trident.labels" $root | nindent 4 }}
    app.kubernetes.io/name: "{{ $secretName }}-secret"
  annotations:
    {{- include "trident.annotations" $root | nindent 4 }}
    argocd.argoproj.io/sync-wave: "2"
stringData:
  username: {{ $backend.credentials.username | quote }}
  password: {{ $backend.credentials.password | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
