apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-mongo-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-mongo
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-mongo
    targetRevision: 21.3.106
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        cluster:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default-mongo
  ignoreDifferences:
    - group: mongodbcommunity.mongodb.com
      kind: MongoDBCommunity
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
