apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-sso
  namespace: openshift-gitops
spec:
  description: Configure Red Hat SSO operator and Keycloak instances
  sourceRepos:
    - http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
  destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: startx-sso
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
