apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-acm
  namespace: openshift-gitops
spec:
  description: Deploy Advanced Cluster Management on OpenShift
  sourceRepos:
    - 'http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: openshift-acm-operator
    - server: https://kubernetes.default.svc
      namespace: startx-acm-observability
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: operators.coreos.com
      kind: OperatorGroup
    - group: operators.coreos.com
      kind: Subscription
    - group: operator.open-cluster-management.io
      kind: MultiClusterHub
