apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-vault-config-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-vault-config
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-vault-config
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        project:
          enabled: false
        operator:
          enabled: false
        vault:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: startx-vault-config
  ignoreDifferences:
    - group: secretsmanager.hashicorp.com
      kind: SecretEngineMount
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
