# Configures MachineHealthCheck, MachineAutoscaler and MachineSet resources
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-machine-machineset
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-machine
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-machine
    targetRevision: 21.3.106
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        cluster:
          id: demo219-g866v
          region: eu-west-2
        machineSet:
          enabled: true
          list:
          - name: app-a
            az: a
            type: app
            ami: ami-0e079f8742280b034
            instanceType: "t3a.large"
            volumeSize: 75
            volumeType: "gp3"
            replicas: 1
            securityGroupName: "demo219-g866v-node"
            subnet_name: "demo219-g866v-subnet-private-eu-west-2a"
          - name: app-b
            az: b
            type: app
            ami: ami-0e079f8742280b034
            instanceType: "t3a.large"
            volumeSize: 75
            volumeType: "gp3"
            replicas: 1
            securityGroupName: "demo219-g866v-node"
            subnet_name: "demo219-g866v-subnet-private-eu-west-2b"
          - name: app-c
            az: c
            type: app
            ami: ami-0e079f8742280b034
            instanceType: "t3a.large"
            volumeSize: 75
            volumeType: "gp3"
            replicas: 1
            securityGroupName: "demo219-g866v-node"
            subnet_name: "demo219-g866v-subnet-private-eu-west-2c"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
