---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aoa-infra-min
  namespace: openshift-gitops
spec:
  description: Deploy Minimal infrastructure components and configurations
  sourceRepos:
    - 'http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/*'
  destinations:
    - server: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-infra-min
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: aoa-infra-min
  source:
    repoURL: https://gitlab.com/startx1/helm.git
    targetRevision: stable
    path: charts/cluster-argocd/
    helm:
      values: |
        context:
          scope: startx
          cluster: default
          environment: infra
          component: argocd
          app: aoa-infra-min
          version: "0.1.0"
        argocd_project:
          enabled: true
        application:
          enabled: true
        argocd_repocreds:
          enabled: true
        project:
          enabled: false
          project:
            enabled: false
            name: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
