# Wave 5 — Deploy the sxapi microservice with service and exposition
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sxapi-dev-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sxapi-dev
  source:
    chart: sxapi
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        sxapi:
          service:
            enabled: true
          expose:
            enabled: true
          version: "0.3.63"
          profile: "prod:start"
          debug: true
          replicas: 1
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    targetRevision: 21.3.205
  destination:
    namespace: demo-sxapi-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
