# Wave 5 — Create the project namespace with RBAC, network policies and quotas
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sxapi-dev-project
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project
  source:
    chart: project
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        project:
          enabled: true
          type: namespace
          name: demo-sxapi-dev
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    targetRevision: 21.3.106
  destination:
    namespace: demo-sxapi-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
