apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sxapi-dev
  namespace: openshift-gitops
spec:
  description: Deploy a sxapi microservice application
  sourceRepos:
    - 'http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: demo-sxapi-dev
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
