{{- if .Values.kraken.enabled -}}
{{- $appName := include "startx.appName" . -}}
{{- $namespace := .Values.project.project.name -}}
---
kind: ConfigMap
apiVersion: v1
immutable: false
metadata:
  name: kraken-scenario-startx-time-node
  namespace: "{{- $namespace -}}"
  labels:
    app.kubernetes.io/name: "kraken-scenario-startx-time-node"
    {{- include "chaos-kraken.labels" $ | nindent 4 }}
  annotations:
    {{- include "chaos-kraken.annotations" $ | nindent 4 }}
data:
  startx_time_node.yml: |
    time_scenarios:
      - action: skew_date
        object_type: node
        label_selector: node-role.kubernetes.io/master
      - action: skew_date
        object_type: node
        label_selector: node-role.kubernetes.io/infra
      - action: skew_date
        object_type: node
        label_selector: node-role.kubernetes.io/worker
      - action: skew_time
        object_type: node
        label_selector: node-role.kubernetes.io/master
      - action: skew_time
        object_type: node
        label_selector: node-role.kubernetes.io/infra
      - action: skew_time
        object_type: node
        label_selector: node-role.kubernetes.io/worker
---
kind: ConfigMap
apiVersion: v1
immutable: false
metadata:
  name: kraken-scenario-startx-time-pod
  namespace: "{{- $namespace -}}"
  labels:
    app.kubernetes.io/name: "kraken-scenario-startx-time-pod"
    {{- include "chaos-kraken.labels" $ | nindent 4 }}
  annotations:
    {{- include "chaos-kraken.annotations" $ | nindent 4 }}
data:
  startx_time_pod.yml: |
    time_scenarios:
      - action: skew_date
        object_type: pod
        namespace: openshift-etcd
        container_name: etcd
        label_selector: app=etcd
      - action: skew_date
        object_type: pod
        namespace: openshift-machine-config-operator
        container_name:
        label_selector: "k8s-app=machine-config-daemon"
      - action: skew_date
        object_type: pod
        namespace: openshift-apiserver
        container_name:
        label_selector: "app=openshift-apiserver-a"
      - action: skew_time
        object_type: pod
        namespace: openshift-etcd
        container_name: etcd
        label_selector: app=etcd
      - action: skew_time
        object_type: pod
        namespace: openshift-machine-config-operator
        container_name:
        label_selector: "k8s-app=machine-config-daemon"
      - action: skew_time
        object_type: pod
        namespace: openshift-apiserver
        container_name:
        label_selector: "app=openshift-apiserver-a"
---
kind: ConfigMap
apiVersion: v1
immutable: false
metadata:
  name: kraken-config-chaos-time
  namespace: "{{- $namespace -}}"
  labels:
    app.kubernetes.io/name: "kraken-config-chaos-time"
    {{- include "chaos-kraken.labels" $ | nindent 4 }}
  annotations:
    {{- include "chaos-kraken.annotations" $ | nindent 4 }}
data:
  config.yaml: |-
    kraken:
      distribution: openshift
      kubeconfig_path: /home/krkn/.kube/config
      exit_on_failure: False
      port: 8081
      publish_kraken_status: False
      signal_address: 0.0.0.0
      signal_state: RUN
      litmus_version: v1.13.6
      litmus_uninstall: False
      litmus_uninstall_before_run: False
      chaos_scenarios:
        - time_scenarios: 
          - scenarios/startx_time_pod.yml
          - scenarios/startx_time_node.yml
    cerberus:
        cerberus_enabled: True
        cerberus_url: {{ $.Values.kraken.cerberusUrl | quote }}
        check_applicaton_routes: True
    performance_monitoring:
        deploy_dashboards: False
        repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"
        kube_burner_binary_url: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v1.7.2/kube-burner-V1.7.2-linux-x86_64.tar.gz"
        capture_metrics: True
        config_path: config/kube_burner.yaml
        metrics_profile_path: config/metrics-aggregated.yaml
        prometheus_url:
        prometheus_bearer_token:
        uuid:
        enable_alerts: False
        alert_profile: config/alerts
    tunings:
        wait_duration: 420
        iterations: 1
        daemon_mode: False
{{- end -}}
