{{- if .Values.kraken.enabled -}}
{{- $appName := include "startx.appName" . -}}
{{- $namespace := .Values.project.project.name -}}
---
kind: ConfigMap
apiVersion: v1
immutable: false
metadata:
  name: kraken-scenario-app-outage
  namespace: "{{- $namespace -}}"
  labels:
    app.kubernetes.io/name: "kraken-scenario-app-outage"
    {{- include "chaos-kraken.labels" $ | nindent 4 }}
  annotations:
    {{- include "chaos-kraken.annotations" $ | nindent 4 }}
data:
  app_outage.yaml: |
    application_outage:
      duration: 60
      namespace: chaos-cerberus
      block: [Ingress, Egress]
{{- end -}}
