{{- if and .Values.ingressControllerSecret.enabled }}
{{- if and .Values.ingressControllerSecret.tls.crt .Values.ingressControllerSecret.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingressControllerSecret.name | default "public-ingress-cert" }}
  namespace: {{ .Values.ingressControllerSecret.namespace | default "openshift-ingress" }}
  labels:
    {{- include "cluster-keepalived.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-keepalived.annotations" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.ingressControllerSecret.tls.crt }}
  tls.key: {{ .Values.ingressControllerSecret.tls.key }}
{{- end }}
{{- end }}
