# Deploys kubevirt-hyperconverged operator in openshift-cnv (dedicated namespace, own OperatorGroup)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-kubevirt-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-kubevirt
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-kubevirt
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        operator:
          enabled: true
          operatorGroup:
            enabled: true
        hyperconvergedCluster:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cnv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
