apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-storage-efs-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-storage-efs
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-storage-efs
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        operator:
          enabled: false
        sharedVolumes:
          enabled: true
          list:
          - name: startx-aws-efs
            namespace: "default"
            accessPointID: "fsap-xxxxxxxxxxxxxxxxx"
            fileSystemID: "fs-xxxxxxxxxxxxxxxxx"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
