apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-mustgather
  namespace: openshift-gitops
spec:
  description: Deploy the MustGather operator on OpenShift
  sourceRepos:
    - 'http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: openshift-operators
    - server: https://kubernetes.default.svc
      namespace: default-mustgather
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
