# Default values for cluster-nexus.

# Application deployment context
context:  &context
  # Name of the global scope for this application (organisational tenant)
  scope: myscope
  # Name of the cluster running this application (platform tenant)
  cluster: default
  # Name of the environment for this application (ex: dev, factory, preprod or prod)
  environment: myenv
  # Component name of this application (logical tenant)
  component: mycomponent
  # Application name (functional tenant, default use Chart name)
  app: default-nexus
  # Version name of this application (default use Chart appVersion)
  version: "3.90.3"

# Deploy a Nexus server instance
nexus:
  # Enable the configuration of the Nexus server
  enabled: false
  # Activate the manager as a helm hook
  hooked: false
  # Name of the deployed instance of NexusRepo
  name: default
  # Namespace of the deployed instance of NexusRepo
  namespace: startx-nexus
  # The applied Nexus config specifications
  spec: |
    ingress:
      enabled: true
      dockerSubdomain: false
      annotations: null
      host: default-nexus.apps.demo219.startx.fr
      name: nexus-default
      additionalRules: null
      dockerIngress:
        annotations: null
        enabled: false
        host: default-nexus-docker.apps.demo219.startx.fr
        name: nexus-docker-default
      tls:
        enabled: false
        secretName: tlsSecretName
      defaultRule: false
    license:
      fileContentsBase64: your_license_file_contents_in_base_64
      secretName: nexus-repo-license
    nexusData:
      pvc:
        accessMode: ReadWriteOnce
        size: 2Gi
      storageClass:
        enabled: false
        name: nexusrepo-storage
        parameters: {}
        provisioner: provisioner
        reclaimPolicy: Retain
        volumeBindingMode: WaitForFirstConsumer
      volumeClaimTemplate:
        enabled: false
    secret:
      nexusSecret:
        enabled: false
        mountPath: /var/nexus-repo-secrets
        name: nexus-secret.json
        nexusSecretsKeyId: super_secret_key_id
        secretKeyfileContentsBase64: secretKeyfileContentsBase64
    service:
      docker:
        enabled: true
        name: nexus-repo-docker-service
        port: 9090
        protocol: TCP
        targetPort: 9090
        type: NodePort
      nexus:
        enabled: true
        name: nexus-repo-service
        port: 80
        protocol: TCP
        targetPort: 8081
        type: NodePort
    statefulset:
      container:
        containerPort: 8081
        env:
          clustered: false
          install4jAddVmParams: '-Xms2703m -Xmx2703m'
          jdbcUrl: null
          nexusInitialPassword: nexusabc
          password: nexus
          user: nexus
          zeroDowntimeEnabled: false
        imageName: 'registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:5188576b552e811ef4fb78d82fd3a57dbfee8f785c2983f1ded96025d4a98197'
        pullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
        terminationGracePeriod: 90
      imagePullSecrets: {}
      livenessProbe:
        failureThreshold: 6
        initialDelaySeconds: 240
        path: /
        periodSeconds: 60
      name: nexusrepo-statefulset
      readinessProbe:
        failureThreshold: 6
        initialDelaySeconds: 240
        path: /
        periodSeconds: 60
      replicaCount: 1


# Configuration of the project (see https://helm-repository.readthedocs.io/en/latest/charts/project)
# openshift-operators already exists as a system namespace - keep disabled
project:
  enabled: false
  context:
    <<: *context
  project:
    enabled: true
    hooked: false
    type: namespace
    name: "startx-nexus"
    display_name: Instance NEXUS
    description: Nexus repository server configured by STARTX

# Configuration of the operator (see https://helm-repository.readthedocs.io/en/latest/charts/operator)
operator:
  enabled: false
  context:
    <<: *context
  subscription:
    enabled: true
    hooked: false
    name: "nexus-repository-ha-operator-certified"
    namespace: "openshift-operators"
    version: "v3.90.3-1"
    operator:
      channel: stable
      name: nexus-repository-ha-operator-certified
      installPlanApproval: Automatic
      # csv: nexus-repository-ha-operator-certified.v3.90.3-1
      source:
        name: certified-operators
        namespace: openshift-marketplace
      config:
        infra: false
  operatorGroup:
    enabled: true
    hooked: false
    name: "global-operators"
    namespace: "openshift-operators"
    providedAPIs: "NexusRepo.v1alpha1.sonatype.com"
