apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - application-cerberus-instance.yaml
  - application-kraken-instance.yaml
  - application-litmus-instance.yaml
  - application-mesh-instance.yaml
  - application-monkey-instance.yaml
