{{- if .Values.externalComponents.redis.enabled -}}
{{- $ns := .Values.project.project.name | default "startx-3scale" -}}
{{- $host := .Values.externalComponents.redis.host -}}
{{- $port := .Values.externalComponents.redis.port | default "6379" -}}
{{- $pass := .Values.externalComponents.redis.password | default "" -}}
{{- $passPrefix := "" -}}
{{- if $pass }}{{- $passPrefix = printf ":%s@" $pass -}}{{- end -}}
{{- $url := printf "redis://%s%s:%s" $passPrefix $host $port -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
  namespace: {{ $ns | quote }}
  labels:
    {{- include "cluster-3scale.labels" . | nindent 4 }}
    app.kubernetes.io/name: "system-redis-secret"
  annotations:
    {{- include "cluster-3scale.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  URL: "{{ $url }}/{{ .Values.externalComponents.redis.systemDb | default "1" }}"
  NAMESPACE: "{{ .Values.externalComponents.redis.systemDb | default "1" }}"
  SENTINELS: ""
  SENTINEL_ROLE: ""
  SENTINEL_USERNAME: ""
  SENTINEL_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
  namespace: {{ $ns | quote }}
  labels:
    {{- include "cluster-3scale.labels" . | nindent 4 }}
    app.kubernetes.io/name: "backend-redis-secret"
  annotations:
    {{- include "cluster-3scale.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  REDIS_STORAGE_URL: "{{ $url }}/{{ .Values.externalComponents.redis.backendStorageDb | default "0" }}"
  REDIS_QUEUES_URL: "{{ $url }}/{{ .Values.externalComponents.redis.backendQueuesDb | default "2" }}"
{{- end -}}
