{{- if .Values.externalComponents.database.enabled -}}
{{- $ns := .Values.project.project.name | default "startx-3scale" -}}
{{- $dbHost := .Values.externalComponents.database.host -}}
{{- $dbPort := .Values.externalComponents.database.port | default "5432" -}}
{{- $dbName := .Values.externalComponents.database.name | default "3scale" -}}
{{- $dbUser := .Values.externalComponents.database.user | default "3scale" -}}
{{- $dbPass := .Values.externalComponents.database.password | default "changeme" -}}
{{- $zyncHost := .Values.externalComponents.zync.host | default $dbHost -}}
{{- $zyncPort := .Values.externalComponents.zync.port | default $dbPort -}}
{{- $zyncName := .Values.externalComponents.zync.name | default "zync" -}}
{{- $zyncUser := .Values.externalComponents.zync.user | default "zync" -}}
{{- $zyncPass := .Values.externalComponents.zync.password | default "changeme" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
  namespace: {{ $ns | quote }}
  labels:
    {{- include "cluster-3scale.labels" . | nindent 4 }}
    app.kubernetes.io/name: "system-database-secret"
  annotations:
    {{- include "cluster-3scale.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  URL: "postgresql://{{ $dbUser }}:{{ $dbPass }}@{{ $dbHost }}:{{ $dbPort }}/{{ $dbName }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: zync
  namespace: {{ $ns | quote }}
  labels:
    {{- include "cluster-3scale.labels" . | nindent 4 }}
    app.kubernetes.io/name: "zync-secret"
  annotations:
    {{- include "cluster-3scale.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ $zyncUser }}:{{ $zyncPass }}@{{ $zyncHost }}:{{ $zyncPort }}/{{ $zyncName }}"
  SECRET_KEY_BASE: "{{ .Values.externalComponents.zync.secretKeyBase | default "changeme_zync_secret_key_base_min_30_chars" }}"
{{- end -}}
