apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-compliance-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-compliance
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-compliance
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        compliance:
          enabled: true
        project:
          project:
            name: "openshift-compliance"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-compliance
  ignoreDifferences:
    - group: compliance.openshift.io
      kind: ScanSetting
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
