apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chaos-monkey
  namespace: openshift-gitops
spec:
  description: Deploy kube-monkey chaos pod killer on OpenShift
  sourceRepos:
    - 'http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/*'
    - 'https://asobti.github.io/kube-monkey/charts/repo'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: chaos-monkey
    - server: https://kubernetes.default.svc
      namespace: default
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: project.openshift.io
      kind: ProjectRequest
    - group: security.openshift.io
      kind: SecurityContextConstraints
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
