# Default values for configuration of a STARTX cluster
# see values.yaml for explanation on each params
context: 
  scope: startx
  cluster: startx-centigpu
  environment: infra
  component: config
  app: startx-machine
  version: "4.18.11"

cluster:
  id: startx-xyzab
  region: eu-west-2
  autoscaler: 
    enabled: false

machineConfigPool: 
  enabled: false
  infra: true
  virt: false
  storage: false
  list: 
  - name: worker
    machineConfigSelector: |-
      matchExpressions:
        - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker]}
    nodeSelector: |-
      matchLabels:
        node-role.kubernetes.io/worker: ""
    paused: false
machineConfig: 
  enabled: false
  kubelet_gc_enabled: false
  kubelet_connectiontimeout_enabled: false
  kubelet_master_maxpodbig: true
  kubelet_worker_maxpodbig: false
  kubelet_protectkerneldefaults: false
  infra_specialconfig: true
  add_scc_netraw: false
  add_clusterimageconfig: false

machineHealthCheck:
  enabled: false
  list: 
  - name: master
    type: master
    maxUnhealthy: 40%
    timeouts: 300s
  - name: worker
    type: worker
    group: worker
    maxUnhealthy: 40%
    timeouts: 300s
  - name: worker-gpu
    type: worker-gpu
    group: worker-gpu
    maxUnhealthy: 40%
    timeouts: 300s
  - name: worker-gpubig
    type: worker-gpubig
    group: worker-gpubig
    maxUnhealthy: 40%
    timeouts: 300s


machineAutoscaler: 
  enabled: false
  list: 
  - name: aworker-gpu-a
    minReplicas: 1
    maxReplicas: 2
  - name: worker-gpu-b
    minReplicas: 0
    maxReplicas: 2
  - name: worker-gpu-c
    minReplicas: 0
    maxReplicas: 2
  - name: worker-gpubig-a
    minReplicas: 0
    maxReplicas: 2
  - name: worker-gpubig-b
    minReplicas: 1
    maxReplicas: 2
  - name: worker-gpubig-c
    minReplicas: 0
    maxReplicas: 2
  - name: worker-a
    minReplicas: 0
    maxReplicas: 2
  - name: worker-b
    minReplicas: 0
    maxReplicas: 2
  - name: worker-c
    minReplicas: 1
    maxReplicas: 2

machineSet: 
  enabled: false
  list: 
  - name: worker-gpu-a
    az: a
    type: worker-gpu
    group: worker-gpu
    ami: ami-00667f67a54be771a
    instanceType: "g6.2xlarge"
    volumeSize: 150
    replicas: 1
  - name: worker-gpu-b
    az: b
    type: app
    group: worker-gpu
    ami: ami-00667f67a54be771a
    instanceType: "g6.2xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-gpu-c
    az: c
    type: app
    group: worker-gpu
    ami: ami-00667f67a54be771a
    instanceType: "g6.2xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-gpubig-a
    az: a
    type: app
    group: worker-gpubig
    ami: ami-00667f67a54be771a
    instanceType: "g7e.2xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-gpubig-b
    az: b
    type: app
    group: worker-gpubig
    ami: ami-00667f67a54be771a
    instanceType: "g7e.2xlarge"
    volumeSize: 150
    replicas: 1
  - name: worker-gpubig-c
    az: c
    type: app
    group: worker-gpubig
    ami: ami-00667f67a54be771a
    instanceType: "g7e.2xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-a
    az: a
    type: app
    group: worker
    ami: ami-00667f67a54be771a
    instanceType: "m5.xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-b
    az: b
    type: app
    group: worker
    ami: ami-00667f67a54be771a
    instanceType: "m5.xlarge"
    volumeSize: 150
    replicas: 0
  - name: worker-c
    az: c
    type: app
    group: worker
    ami: ami-00667f67a54be771a
    instanceType: "m5.xlarge"
    volumeSize: 150
    replicas: 1
