#!/bin/bash

# shellcheck disable=SC2034
SXH_AWS_CONF_PATH=~/.aws
SXH_AWS_CMD=aws


#####################
## GENERIC S3 FUNCTIONS

# list all buckets
function awsS3LsBuckets {
    ${SXH_AWS_CMD} s3 ls
}

# list content of a bucket
function awsS3LsBucket {
    local bucket=${1:-$HELM_REPO_AWSBUCKET}
    ${SXH_AWS_CMD} s3 ls s3://${bucket} --recursive
}

# Upload a single file to the S3 bucket
function awsS3UploadFile {
    local file=${1:-"/tmp/default.txt"}
    local path=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    local filename
    filename="$(basename -- "$file")"
    ${SXH_AWS_CMD} s3 cp "${file}" s3://${bucket}/${path}/${filename}
}

# Upload a local directory to the S3 target path
function awsS3UploadDir {
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    local options=${4:-""}
    # shellcheck disable=SC2086
    ${SXH_AWS_CMD} s3 sync "${localpath}" s3://${bucket}/${remotepath} ${options}
}

# Download a single file from the S3 bucket
function awsS3DownloadFile {
    local file=${1:-"/tmp/default.txt"}
    local path=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    local filename
    filename="$(basename -- "$file")"
    ${SXH_AWS_CMD} s3 cp s3://${bucket}/${path}/${filename} "${file}"
}

# Download an S3 path into a local directory
function awsS3DownloadDir {
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    local options=${4:-""}
    # shellcheck disable=SC2086
    ${SXH_AWS_CMD} s3 sync s3://${bucket}/${remotepath} "${localpath}" ${options}
}

# Test whether AWS CLI credentials are configured and reachable
function awsTestAPIAccess {
    ${SXH_AWS_CMD} s3 ls &>/dev/null
    echo $?
}


#####################
## ACCESS GUARD

# Exit with an error if AWS credentials are not configured
function awsAccessMandatory {
    if [[ $(awsTestAPIAccess) != "0" ]]; then
        echo -e "\e[31mError\e[0m aws cli must be configured using 'aws configure' command"
        exit 1
    fi
}


#####################
## DISPLAY / WRAPPER FUNCTIONS

# Display all buckets
function awsS3BucketsList {
    awsAccessMandatory
    echo -e "\e[33mList\e[0m buckets for default AWS config"
    awsS3LsBuckets
}

# Display the content of a bucket
# shellcheck disable=SC2120
function awsS3BucketList {
    awsAccessMandatory
    local bucket=${1:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[33mList\e[0m content of the $bucket bucket"
    awsS3LsBucket "$bucket"
}

# Upload one file to the S3 bucket
function awsS3FileUpload {
    awsAccessMandatory
    local file=${1:-"default.txt"}
    local path=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[33mUpload\e[0m $file → s3://$bucket/$path"
    awsS3UploadFile "$file" "$path" "$bucket"
}

# Sync a local directory to S3 (no delete)
function awsS3SyncUpload {
    awsAccessMandatory
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[33mUpload\e[0m $localpath → s3://$bucket/$remotepath"
    awsS3UploadDir "$localpath" "$remotepath" "$bucket"
}

# Sync a local directory to S3 (with remote delete for removed files)
function awsS3SyncUploadDelete {
    awsAccessMandatory
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[33mUpload\e[0m $localpath → s3://$bucket/$remotepath (--delete)"
    awsS3UploadDir "$localpath" "$remotepath" "$bucket" "--delete"
}

# Download one file from S3
function awsS3FileDownload {
    awsAccessMandatory
    local file=${1:-"default.txt"}
    local path=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[93mDownload\e[0m s3://$bucket/$path → $file"
    awsS3DownloadFile "$file" "$path" "$bucket"
}

# Sync an S3 path into a local directory (no delete)
function awsS3SyncDownload {
    awsAccessMandatory
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[93mDownload\e[0m s3://$bucket/$remotepath → $localpath"
    awsS3DownloadDir "$localpath" "$remotepath" "$bucket"
}

# Sync an S3 path into a local directory (with local delete for removed files)
function awsS3SyncDownloadDelete {
    awsAccessMandatory
    local localpath=${1:-".reposync"}
    local remotepath=${2:-""}
    local bucket=${3:-$HELM_REPO_AWSBUCKET}
    echo -e "\e[93mDownload\e[0m s3://$bucket/$remotepath → $localpath (--delete)"
    awsS3DownloadDir "$localpath" "$remotepath" "$bucket" "--delete"
}


#####################
## ROUTER FUNCTIONS

# Download full S3 repo into local .reposync
function routerSyncFromS3 {
    awsS3SyncDownload "${HELM_REPO_LOCALSYNC}" ""
}

# Upload full local .reposync to S3 (with remote delete)
function routerSyncToS3 {
    awsS3SyncUploadDelete "${HELM_REPO_LOCALSYNC}" ""
}
