#!/bin/bash
# sx-helm configuration - sourced by .tools/cli and Makefile
# Edit this file to change global defaults; do not hardcode values in cli or sx-helm.

# -- Repository versioning ------------------------------------------------------
STABLE_MAINRELEASE="21"
STABLE_SUBRELEASE="3"
SXV4_CONSOLE_VERSION="${STABLE_MAINRELEASE}.${STABLE_SUBRELEASE}.1"

# -- Git branches ---------------------------------------------------------------
WORK_BRANCH="devel"
MASTER_BRANCH="master"
STABLE_BRANCH="stable"

# -- Git remotes ----------------------------------------------------------------
GITHUB_REPOSITORY="helm-repository"
GITHUB_REPONAME="origin"
GITLAB_REPONAME="gitlab"

# -- Helm S3 repository --------------------------------------------------------
HELM_REPO_AWSBUCKET="sx-helm-repository-prod"
HELM_REPO_AWSDC="eu-west-3"
HELM_REPO_BASEURL="http://${HELM_REPO_AWSBUCKET}.s3-website.${HELM_REPO_AWSDC}.amazonaws.com"
HELM_REPO_SUBDEFAULT="stable"
HELM_REPO_SUBDEV="devel"

# -- Package signing -----------------------------------------------------------
SXHELM_SIGN="enabled"
SXHELM_SIGN_KEY="dev@startx.fr"
SXHELM_SIGN_KEYRING="${HOME}/.gnupg/secring.gpg"
SXHELM_SIGN_KEYPASSPHRASEFILE="${HOME}/.ssh/pgp-dev_startx-private_key-passphrase.txt"

# -- Documentation behaviour ---------------------------------------------------
# Set to "true" to auto-append history rows and sync README to docs/charts/
DOC_ADD_HISTORY="true"

# -- Repository archive lists --------------------------------------------------
# Space-separated OCP minor release numbers for "active archive" repos.
# These are published by: sx-helm archive / make archive
# Add a new number here when an OCP release enters archive status.
HELM_REPO_ARCHIVE_RELEASES="20 19 18 16 14"

# Space-separated OCP minor release numbers for "legacy archive" repos.
# These are published by: sx-helm archiveLegacy / make archive-legacy
# Move numbers here from HELM_REPO_ARCHIVE_RELEASES when a release becomes legacy.
HELM_REPO_LEGACY_RELEASES="17 15 13 12 11 10 9 8 7 6x"
