apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-vault-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-vault
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-vault
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        project:
          enabled: false
        vault:
          enabled: true
          global:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: startx-vault
  ignoreDifferences:
    - group: vault.banzaicloud.com
      kind: Vault
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
