apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-vault
  namespace: openshift-gitops
spec:
  description: Deploy HashiCorp Vault in startx-vault namespace
  sourceRepos:
    - http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
  destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: startx-vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
