apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-kraken-project
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: chaos-kraken
  source:
    chart: chaos-kraken
    helm:
      valueFiles:
        - values-startx-project.yaml
      values: |
        project:
          enabled: true
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    targetRevision: 21.3.135
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
