apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-ansible-project
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: startx-ansible
    server: https://kubernetes.default.svc
  project: cluster-ansible
  source:
    chart: cluster-ansible
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        project:
          enabled: true
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    targetRevision: 21.3.107
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
