# Default values for cluster-acs.

# Application deployment context
context:  &context
  # Name of the global scope for this application (organisational tenant)
  scope: myscope
  # Name of the cluster running this application (platform tenant)
  cluster: default
  # Name of the environment for this application (ex: dev, factory, preprod or prod)
  environment: myenv
  # Component name of this application (logical tenant)
  component: mycomponent
  # Application name (functional tenant, default use Chart name)
  app: default-acs
  # Version name of this application (default use Chart appVersion)
  version: "4.11.0"

# configuration of the acs service
acs:
  # Enable the deployment of the acs service
  enabled: true
  # Deploy CS only on infra nodes
  infra: false
  # configuration of the multi-cluster Hub
  central:
    # Enable the deployment of the reporting-operator service
    enabled: true
    # Activate the manager as a helm hook
    hooked: false
    # name of the central deployment
    name: "default"
  # configuration of the scanner service
  scanner:
      # Enable the deployment of the scanner service
      enabled: true

# Configuration of the project (see https://helm-repository.readthedocs.io/en/latest/charts/project)
project: 
  enabled: false
  context: 
    <<: *context
  project: 
    enabled: true
    type: namespace
    name: "startx-acs"
    display_name: Operator ACS
    description: ACS operators configured by startx
  rbac: 
    enabled: true
    groups: 
    - id: devops-view
      name: devops
      role: view
    - id: ops-admin
      name: ops
      role: admin
  networkpolicy: 
    enabled: false
  limits: 
    enabled: false
  quotas: 
    enabled: false

# Configuration of the operator (see https://helm-repository.readthedocs.io/en/latest/charts/operator)
operator:
  enabled: false
  context: 
    <<: *context
  subscription:
    enabled: true
    name: "rhacs-operator"
    namespace: "openshift-operators"
    version: "v4.11.0"
    operator: 
      channel: "stable"
      name: rhacs-operator
      installPlanApproval: Automatic
      # csv: rhacs-operator
      source: 
        name: redhat-operators
        namespace: openshift-marketplace
      config: 
        infra: false
  operatorGroup:
    enabled: true
    target: "all-ns"
    name: "startx-rhacs"
    namespace: "openshift-operators"
    providedAPIs: "Central.v1alpha1.platform.stackrox.io,SecuredCluster.v1alpha1.platform.stackrox.io"
