# Deploys GitLab instance in startx-gitlab namespace (disabled by default - requires storage and domain config)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-gitlab-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-gitlab
  source:
    repoURL: http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
    chart: cluster-gitlab
    targetRevision: 21.3.199
    helm:
      valueFiles:
        - values-startx_noinfra.yaml
      values: |
        gitlab:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: startx-gitlab
  ignoreDifferences:
    - group: apps.gitlab.com
      kind: GitLab
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
