apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  description: Configure core OpenShift cluster services and logging operators
  sourceRepos:
    - http://sx-helm-repository-prod.s3-website.eu-west-3.amazonaws.com/stable
  destinations:
    - namespace: startx-config
      server: https://kubernetes.default.svc
    - namespace: openshift-config
      server: https://kubernetes.default.svc
    - namespace: openshift-image-registry
      server: https://kubernetes.default.svc
    - namespace: openshift-ingress
      server: https://kubernetes.default.svc
    - namespace: openshift-ingress-operator
      server: https://kubernetes.default.svc
    - namespace: openshift-monitoring
      server: https://kubernetes.default.svc
    - namespace: openshift-distributed-tracing
      server: https://kubernetes.default.svc
    - namespace: openshift-operators
      server: https://kubernetes.default.svc
    - namespace: openshift-operators-redhat
      server: https://kubernetes.default.svc
    - namespace: default-sosreport
      server: https://kubernetes.default.svc
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
