# Default values for configuration of a STARTX cluster
# see values.yaml for explanation on each params
context: &context
  scope: startx
  cluster: default
  environment: infra
  component: kargo
  app: demo-kargo
  version: "4.20.0"
kargo:
  enabled: false
  hooked: false
  name: default
  spec: |
    daemonNodeSelector:
      node-role.kubernetes.io/worker: ""
    # profile:
    # - name: "profile1"
    #   interface: "enp134s0f0"
    #   kargo4lOpts: "-s -2"
    #   phc2sysOpts: "-a -r"
    # recommend:
    # - profile: "profile1"
    #   priority: 4
    #   match:
    #   - nodeLabel: "node-role.kubernetes.io/worker"
project: 
  enabled: false
  context: 
    <<: *context
  project: 
    enabled: true
    hooked: false
    type: namespace
    name: "demo-kargo"
    display_name: "Demo Kargo"
    requester: startx
    description: Demo of Kargo configured by STARTX
operator:
  enabled: false
  context: 
    <<: *context
  subscription:
    enabled: false
  operatorGroup:
    enabled: false